### ISSUE TITLE
There needs to be a folder structure in place for this repository to become usable

### ISSUE THREAD

**Issue by Hugoberry** [tycho01/pquery#16]
Have you guys considered coming up with a folder structure for all of these functions? I was discouraged to check on the project details just because the descriptions of this repo are way down at the bottom.

**Comment by tycho01** [comment]
Hey,
On a related note, I'd intended to have folders and have them relate to the folders in Power Query, but limitations to the exposed VBA functionality meant it wasn't possible to programmatically make use of the Power Query folders iirc...
That said, I can't currently think of potential issues with just using folders anymore, though I'm under the impression I had considered it at the time. If it does work for you, feel free to send a PR though.
